require("config.autocmds")
require("config.diagnostics")
require("config.keymaps")
require("config.lsp")
require("config.options")
require("config.packui")
require("config.statusline")
require("config.tabline")
